### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by SBero** [Readify/httpstatus#35]
I thought I'd ask -

What are the terms of usage?

Is the server/bandwidth being donated by Microsoft?

**Comment by aaronpowell** [comment]
umm, why?

**Comment by SBero** [comment]
Well for instance, if I was looking to use the service in an open source project where I wanted a timestamp from a server but didn't want to set it up, could the service be used? e.g. Make a call to get a 200 for the timestamp value.

**Comment by aaronpowell** [comment]
We don't send any specific timestamp back, unless you're planning on relying on the `Date` header.

Any sort of Acceptable Usage Policy isn't something we've had to publish so far (and if we did I'd model it on [the HIBP one](https://haveibeenpwned.com/API/v2#AcceptableUse)) since the traffic has never warranted it.

I pay for it myself, if it gets to the point that I have to start questioning the amount being paid, well that's when I'll look at how best to address it.

**Comment by cuongluu8** [comment]
Rather than raising a new issue, just thought I'd ask here.....
Basically I want to know if it is possible to override the response body with a custom json object?

**Comment by aaronpowell** [comment]
@cuongluu8 I would suggest asking your question as a separate issue as it's unrelated to the question that is being asked in this thread.

**Comment by aaronpowell** [comment]
I'm closing this thread due to inactivity.
