### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by liftoff-rating-scheme** [Readify/httpstatus#41]
Hello, I found your website and thought it would be useful to test some Angular HTTP calls. However, since everything fails CORS, it doesn't work at all.

Would it be possible to add a query string parameter or something to enable CORS for situations such as this?

**Comment by aaronpowell** [comment]
https://github.com/Readify/httpstatus/pull/29 should've added CORS support.

Got a sample somewhere I can see of the issue you're experiencing?

**Comment by aaronpowell** [comment]
Hi @liftoff-rating-scheme - are you able to provide repo steps for this issue?

**Comment by mvodkin** [comment]
I'm getting CORS issues when using `'content-type': 'application/json'` headers.

When I run
```javascript
fetch('https://httpstat.us/200', { headers: { 'content-type': 'application/json' } })
  .then(r => r.json())
  .then(console.log);
```

in a chrome console, I get an error:

`Fetch API cannot load https://httpstat.us/200. Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.`

I think it may have something to do with this https://stackoverflow.com/a/30554385/6938822

**Comment by sideshowbarker** [comment]
@mvodkin The problem you describe in https://github.com/Readify/httpstatus/issues/41#issuecomment-336996359 will go away if you remove the unnecessary<br> `{ headers: { 'content-type': 'application/json' } }` from that fetch call.

That fetch call is making a GET request, right? Adding a `content-type` header to a GET request has no effect, because for a GET request there’s no request payload/body to set the content-type for…

**Comment by aaronpowell** [comment]
@mvodkin as @sideshowbarker points out the `content-type` header doesn't do anything on a `GET` reqeuest, but my guess is you were wanting JSON returned as the response, for that you want the `Accept` header.

That said, it would still fail because we didn't set the `Access-Control-Allow-Headers` appropriately (well, at all 😛). I've just pushed a58b474 which will fix that (should be deployed shortly).

**Comment by aaronpowell** [comment]
@mvodkin @liftoff-rating-scheme Are you still experiencing the issues raised here or can we close this?

**Comment by aaronpowell** [comment]
What status code are you getting and for what request are you making?

Are you able to provide a [HAR](https://developers.google.com/web/tools/chrome-devtools/network-performance/reference#save-as-har) of your error?

**Comment by sebelga** [comment]
I receive the status I ask for ... but on the OPTIONS request. When we make Ajax call (from Angular for ex), on external domain there is first an OPTIONS request on the server to read the Headers. This is where you have to return a 200 Http status and not the status we asked.
The browser will then make a second request, a GET request and then only you return the Http status asked.

**Comment by sideshowbarker** [comment]
@sebelga Exactly that URL(s) are you testing with?

Looking at PR #29 and c5f85f3, it seems expected that http://httpstat.us/400/ will always return a 400 — even for an OPTIONS request — while http://httpstat.us/400/cors will return a 200 for an OPTIONS:

```
$ curl -I -X OPTIONS http://httpstat.us/400/
HTTP/1.1 400 Bad Request
```
```
$ curl -I -X OPTIONS http://httpstat.us/400/cors
HTTP/1.1 200 OK
```

**Comment by sebelga** [comment]
Have a look at how https://httpbin.org/ do it. (test it with a cross domain Ajax call from localhost for ex.)
You will see that the OPTIONS Preflight request **returns a 200**.

> A CORS preflight request is a CORS request that checks to see if the CORS protocol is understood. It is an OPTIONS request, using three HTTP request headers: Access-Control-Request-Method, Access-Control-Request-Headers, and the Origin header.
https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request

Then the browser will send a GET request.

**Comment by sideshowbarker** [comment]
@sebelga Can you answer the question at https://github.com/Readify/httpstatus/issues/41#issuecomment-382883399?

Exactly what http://httpstat.us URL(s) are you testing with?

If you test with, for example, http://httpstat.us/400/cors you’ll find the CORS behavior already works the way you describe in https://github.com/Readify/httpstatus/issues/41#issuecomment-383596206.

But if you test with http://httpstat.us/400/, the CORS behavior won’t work — but that’s expected, because http://httpstat.us/400/ is intentionally not CORS-enabled. You must instead use the corresponding http://httpstat.us/400/cors URL.

So whatever http://httpstat.us URLs you’re trying, if they don’t end in `/cors` then they’re not going to work as expected when you make requests to them from frontend JavaScript code — but if you append `/cors` to them, they will work as expected.

**Comment by sebelga** [comment]
Ah ok, I was not aware of the `/cors` url path. Thanks for the quick reply!

**Comment by MathieuPuech** [comment]
could be good to document this on http://httpstat.us/

**Comment by mderriey** [comment]
@MathieuPuech We would gladly accept a pull request.

The home page view is located here: <https://github.com/Readify/httpstatus/blob/master/src/Teapot.Web/Views/Status/Index.cshtml>

**Comment by MathieuPuech** [comment]
@mderriey I'm not a C# expert, I don't have Visual Studio locally so I can't verify if it's working but I suppose it could work with the PR #81

**Comment by mderriey** [comment]
Fantastic @MathieuPuech, thanks a lot!
