### ISSUE TITLE
the 408 should not answer

### ISSUE THREAD

**Issue by jhonyourangel** [Readify/httpstatus#58]
the 408 should not answer, this way we generate the error on our side.
The lib that i am using should not get a response and raise a 408.

does this make any sense to you ?

**Comment by Meligy** [comment]
Hi Ion,
The spec says that the server is the one that returns the HTTP response.

Quoting from [the HTTP 1.1 spec](https://tools.ietf.org/html/rfc7231#section-6.5.7):

> A server SHOULD send the "close" connection option
   (Section 6.1 of [RFC7230]) in the response, since 408 implies that
   the server has decided to close the connection rather than continue
   waiting.

Also [explained by MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/408) as follows:

> The HyperText Transfer Protocol (HTTP) 408 Request Timeout response status code means that the server would like to shut down this unused connection. It is sent on an idle connection by some servers, even without any previous request by the client.
>
> A server should send the "close" Connection header field in the response, since 408 implies that the server has decided to close the connection rather than continue waiting.
>
> This response is used much more since some browsers, like Chrome, Firefox 27+, and IE9, use HTTP pre-connection mechanisms to speed up surfing.
>
> > Note: some servers merely shut down the connection without sending this message.

**Comment by jhonyourangel** [comment]
Ok, thank you and sorry.

I didn’t look at the specs, I was speculating.

Thank you again

**Comment by Meligy** [comment]
No problem.
Cheers,
